language: bash
os: linux
arch: 
  - ppc64le  
  - s390x
  - amd64
script:
  -  curl -i -X POST -H 'Content-Type: application/json' -d '{"text": "hello world"}' https://test-mm.cloud.mattermost.com/hooks/hpwmkw869iyb5fa5sk8rbimkny

      

